food/urls.py
from . import views
from django.urls import path


app_name= "food"
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:item_id>/',views.details,name='details'),
    path('item/',views.item, name='item'),
    path('add/',views.create_item, name='create_item'),
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),

]

menu_app/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',users_views.register),
]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    item_name=models.CharField(max_length=200)
    item_dsc=models.CharField(max_length=500)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=600,default="https://www.google.com/search?q=pizza+pic&rlz=1C1CHBF_enIN1041IN1042&sxsrf=AB5stBiKdXwdVAUlNf-UGHGzJ5nS2UmnCA:1690453289196&tbm=isch&source=iu&ictx=1&vet=1&fir=vwyNmrlxb87lKM%252C5xpz_Vm2ema2NM%252C%252Fm%252F0663v%253BOt0IjAyD4C7f_M%252CL_YY9OWBaDG7sM%252C_%253BefJ23c2_JH_n7M%252CbBq_NwtYzsoXvM%252C_%253BSoPN2gMsF42S-M%252CbJrwjubfhkn9gM%252C_%253BaiM4Q7-DR5ureM%252CSeOWqVcLRTzMfM%252C_%253BIEfM_7QrpfT8ZM%252CWYOf39ozq1-2MM%252C_&usg=AI4_-kSWCKjgsj8AMKRYwuYXn0U8aeCa0g&sa=X&ved=2ahUKEwiIhb-e1a6AAxWLbmwGHZuqC-UQ_B16BAhIEAE#imgrc=vwyNmrlxb87lKM")

users/models.py
from django.db import models

# Create your models here.

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model= Item
        fields = ['item_name','item_dsc','item_price','item_image']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from .forms import *
# Create your views here.

def index(request):
    item_list=Item.objects.all()
    context={
        'item_list':item_list,

    }
    return render(request,'food/index.html',context)

def details(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item
    }
    return render(request,'food/details.html',context)


def item(request):
    return HttpResponse('<h1>items all</h1')

def create_item(request):
    form=ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render (request,'food/form_item.html',{'form':form})

def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None ,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/form_item.html',{'form':form,'item':item})

def delete_item(request, id):
    item=Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('food/index')
    return render(request,'food/delete_item.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"welcome to {username}, success full create account for you ")
            return redirect("food:index")

    else:

        form = UserCreationForm()
    return render(request,"users/register.html", {'form':form})

food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>base level</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Food_App</a>

    <div class="navbar">
        <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add_item</a>
        <a class="nav-item nav-link" href="#">Delete_item</a>
        <a class="nav-item nav-link" href="#">view_item</a>

    </div>
</nav>
{% block body%}
{% endblock %}
</body>
</html>

food/templates/food/delete_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% csrf_token %}
<form method="POST">
    <h1> are you to delete is item {{item.item_name}} ok </h1>
    <button type="button">comfirm</button>

</form>
</body>
</html>

food/templates/food/details.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
     <<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
{% block body %}
<div class="row">
    <div class="col-md-6">
        <img class="card" height="208px"  src="{{item.item_image}}">

    </div>
    <div class="col=md-4">
        <h1>{{ item.item_name }}</h1>
       <h4>{{ item.item_dsc }}</h4>
       <h1> $: {{ item.item_price }}</h1>
        <a href="{% url 'food:delete_item' item.id %}"><h6>Delete_Item</h6></a>
    </div>

</div>

{% endblock%}
</body>
</html>

food/templates/food/form_item.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form}}
    <button type="button">save</button>

</form>
</body>
</html>

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>

{% block body %}
{% for i in item_list %}
     <div class="row">
         <div class="col-md-3 offset-md-2">
             <img class="card" height="150px" src="{{ i.item_image }}">
         </div>
         <div class="col-md-3" >
             <h3>{{ i.item_name }}</h3>
             <h5>{{ i.item_dsc }}</h5>
             <h4>$:{{ i.item_price }}</h4>
         </div>
         <div class="col-md-2" >
             <h3><a href="{% url 'food:details' i.id %}" class="btn btn-success">Details</a></h3>
         </div>
         {% for message in messages %}
             {{ massage.messages }}

         {% endfor %}

     </div>
{% endfor %}
{% endblock %}




</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">SignUp</button>

</form>

</body>
</html>